### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ghost** [Jarmill/peak#1]
I am trying to get the demo/peak_sir.m example running. The following error is probably related to not having all dependencies required. What do you think?

```
>> peak_sir
Unrecognized function or variable 'sdpsettings'.

Error in peak_estimate (line 424)
mset(sdpsettings('solver', options.solver));

Error in peak_sir (line 88)
    out = peak_estimate(p_opt, order);
```

**Comment by Jarmill** [comment]
Mahdiar,

This is indeed due to a YALMIP dependency.

YALMIP is available at https://github.com/yalmip/YALMIP, https://yalmip.github.io/.

-Jared
